# Generated by Django 5.0.4 on 2024-05-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('constituency', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='captured_photos/')),
            ],
        ),
    ]
