# Generated by Django 5.0.4 on 2024-05-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0002_alter_voter_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='photo',
        ),
        migrations.AddField(
            model_name='voter',
            name='voteid',
            field=models.CharField(default='?', max_length=100),
        ),
    ]
