# Generated by Django 5.0.4 on 2024-05-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0005_voter_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='photo',
        ),
    ]
