# Generated by Django 5.0.4 on 2024-05-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0006_remove_candidate_constituency_remove_candidate_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apreg',
            fields=[
                ('ad', models.IntegerField(primary_key=True, serialize=False)),
                ('sap', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pollsap',
            fields=[
                ('ad', models.IntegerField(primary_key=True, serialize=False)),
                ('td', models.IntegerField()),
                ('ys', models.IntegerField()),
                ('no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pollsts',
            fields=[
                ('ad', models.IntegerField(primary_key=True, serialize=False)),
                ('tr', models.IntegerField()),
                ('co', models.IntegerField()),
                ('bj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tsreg',
            fields=[
                ('ad', models.IntegerField(primary_key=True, serialize=False)),
                ('ste', models.CharField(max_length=15)),
            ],
        ),
    ]
