# Generated by Django 5.0.4 on 2024-05-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0007_apreg_pollsap_pollsts_tsreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apreg',
            name='ad',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
