# Generated by Django 5.0.4 on 2024-06-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0008_alter_apreg_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='signr',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('country', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pollsap',
            name='ad',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pollsts',
            name='ad',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
