# Generated by Django 5.0.4 on 2024-06-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0009_signr_alter_pollsap_ad_alter_pollsts_ad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apreg',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Pollsap',
        ),
        migrations.DeleteModel(
            name='Pollsts',
        ),
        migrations.DeleteModel(
            name='Tsreg',
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
